# yazi.toml
[mgr]
show_hidden = true

[preview]
tab_size = 2
max_width = 600
max_height = 900
image_filter = "lanczos3"
image_threshold = 50

[[plugin.prepend_previewers]]
url = "*.md"
run = 'faster-piper -- CLICOLOR_FORCE=1 glow -s=dark -w=$w < "$1"'
